# Generated by Django 5.2.13 on 2026-04-18 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('missing_fields', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_path', models.CharField(blank=True, max_length=512)),
                ('template_pack', models.CharField(default='housing_tribunal_pack', max_length=64)),
                ('privacy_mode', models.CharField(choices=[('ephemeral', 'Ephemeral (wipe on download)'), ('auto_expire', 'Auto-expire (24h)'), ('retained', 'Retained (manual delete)')], default='auto_expire', max_length=16)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('ready', 'Ready'), ('generated', 'Generated')], default='incomplete', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docforge.extractedrecord')),
            ],
            options={
                'ordering': ['template_key'],
            },
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='docforge.uploadsession'),
        ),
        migrations.AlterUniqueTogether(
            name='extractedrecord',
            unique_together={('session', 'row_index')},
        ),
    ]
